name: momento_booth
description: Opensource photobooth application

publish_to: "none"
version: 0.9.2+96

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter: { sdk: flutter }

  # i18n
  flutter_localizations: { sdk: flutter }
  intl: any

  # UI
  auto_size_text: 3.0.0
  fluent_ui: 4.9.0
  go_router: 14.2.0
  flutter_svg: 2.0.10+1
  animated_text_kit: 4.2.2
  figma_squircle: 0.5.3
  flutter_scroll_shadow: 1.2.4
  flutter_layout_grid: 2.0.7
  pretty_qr_code: 3.3.0
  confetti: 0.7.0
  wave: 0.2.2
  texture_rgba_renderer: { git: https://github.com/h3x4d3c1m4l/flutter_texture_rgba_renderer }
  lottie: 3.1.2
  font_awesome_flutter: 10.7.0
  smooth_scroll_multiplatform: 1.0.8
  widgetbook: 3.8.0
  widgetbook_annotation: 3.1.0
  flex_color_picker: 3.5.1

  # Printscreen/Image processing
  screenshot: 3.0.0
  image: 4.2.0

  # MVC
  mobx: 2.3.3+2
  flutter_mobx: 2.2.1+1

  # Models
  freezed_annotation: 2.4.1
  json_annotation: 4.9.0

  # Rust library/Interop
  rust_lib_momento_booth: { path: rust_builder }
  ffi: 2.1.2
  flutter_rust_bridge: 2.0.0

  # Printing
  printing: 5.13.1
  pdf: 3.11.0

  # System
  path_provider: 2.1.3
  path: ^1.9.0
  window_manager: 0.3.9
  file_selector: 1.0.3
  win32: 5.5.1

  # Log and error handling
  talker: 4.3.2
  talker_flutter: 4.3.2
  sentry_flutter: 8.3.0

  # Sound output
  just_audio: 0.9.38
  just_audio_media_kit: 2.0.4
  media_kit_libs_linux: 1.1.3
  media_kit_libs_windows_audio: 1.0.9

  # Storage
  flutter_secure_storage: 9.2.2
  toml: 0.15.0

  # Networking
  http: 1.2.1
  http_parser: 4.0.2
  mqtt5_client: 4.2.5

  # Misc
  get_it: 7.7.0
  meta: any
  synchronized: 3.1.0+1
  collection: 1.18.0
  dart_casing: 3.0.1
  package_info_plus: 8.0.0
  lemberfpsmonitor: 0.0.3+6
  crypto: 3.0.3
  draggable_scrollbar: 0.1.0
  csslib: 1.0.0

dev_dependencies:
  # UI
  widgetbook_generator: 3.8.0

  # MVC
  mobx_codegen: 2.6.1

  # Code quality
  flutter_lints: 4.0.0

  # Models
  freezed: 2.5.2
  json_serializable: 6.8.0

  # Code generation
  build_runner: 2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/bitmap/
    - assets/svg/
    - assets/fonts/brandon_grotesque/
    - assets/scripts/
    - assets/sounds/

  fonts:
    - family: Brandon Grotesque
      fonts:
        - asset: assets/fonts/brandon_grotesque/Brandon_light.otf
          weight: 300
