name: momento_booth
description: Opensource photobooth application

publish_to: "none"
version: 0.6.6+78

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # i18n
  flutter_localizations:
    sdk: flutter
  intl: 0.18.1

  # UI
  auto_size_text: 3.0.0
  fluent_ui: 4.7.7
  go_router: 12.1.0
  flutter_svg: 2.0.9
  animated_text_kit: 4.2.2
  flutter_scroll_shadow: 1.2.3
  flutter_layout_grid: 2.0.5
  pretty_qr_code: 3.0.0
  confetti: 0.7.0
  wave: 0.2.2
  texture_rgba_renderer:
    git: https://github.com/h3x4d3c1m4l/flutter_texture_rgba_renderer
  lottie: 2.7.0

  # Printscreen/Image processing
  screenshot: 2.1.0
  image: 4.1.3

  # MVC
  mobx: 2.2.1
  flutter_mobx: 2.1.1

  # Models
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1

  # Interop
  ffi: 2.1.0
  flutter_rust_bridge: 1.82.3

  # Printing
  printing: 5.11.1
  pdf: 3.10.6

  # System
  path_provider: 2.1.1
  path: 1.8.3
  window_manager: 0.3.7
  file_selector: 1.0.1
  win32: 5.0.9

  # Log and error handling
  loggy: 2.0.3
  flutter_loggy: 2.0.2
  sentry_flutter: 7.12.0

  # Sound output
  just_audio: 0.9.35
  just_audio_windows: 0.2.0
  just_audio_mpv: 0.1.7

  # Misc
  meta: 1.9.1
  toml: 0.14.0
  synchronized: 3.1.0
  collection: 1.17.2
  mqtt5_client: 4.0.3
  dart_casing: 3.0.1
  package_info_plus: 4.2.0
  lemberfpsmonitor: 0.0.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # MVC
  mobx_codegen: 2.4.0

  # Code quality
  flutter_lints: 3.0.1

  # Models
  freezed: 2.4.5
  json_serializable: 6.7.1

  # Code generation
  build_runner: 2.4.6
  ffigen: 8.0.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/bitmap/
    - assets/svg/
    - assets/fonts/brandon_grotesque/
    - assets/scripts/
    - assets/sounds/

  shaders:
    - assets/shaders/plasma_waves.frag

  fonts:
    - family: Brandon Grotesque
      fonts:
        - asset: assets/fonts/brandon_grotesque/Brandon_light.otf
          weight: 300

scripts:
  run: rps install all && rps generate all
  install:
    all: rps install flutter && rps install cargo-expand && rps install flutter_rust_bridge_codegen && rps install deps
    flutter: fvm install
    cargo-expand: cargo install cargo-expand
    flutter_rust_bridge_codegen: cargo install flutter_rust_bridge_codegen --version 1.82.3
    deps: fvm flutter pub get
  generate:
    all: rps generate l10n && rps generate rust_bridge && rps generate build_runner_targets
    l10n: fvm flutter gen-l10n
    rust_bridge:
      $script:
        $default: flutter_rust_bridge_codegen --rust-input rust/src/dart_bridge/api.rs --dart-output lib/rust_bridge/library_api.generated.dart --rust-output rust/src/dart_bridge/ffi_exports.rs --skip-add-mod-to-lib --no-build-runner
        $macos: flutter_rust_bridge_codegen --rust-input rust/src/dart_bridge/api.rs --dart-output lib/rust_bridge/library_api.generated.dart --rust-output rust/src/dart_bridge/ffi_exports.rs --c-output macos/Runner/bridge_generated.h --skip-add-mod-to-lib --no-build-runner
    build_runner_targets: fvm dart run build_runner build --delete-conflicting-outputs
  update:
    rust-install: rustup update
  docs:
    install-deps: cargo install mdbook mdbook-mermaid mdbook-admonish
    build:
      $before: $docs install-deps
      $script: mdbook build documentation
