[package]
name = "rust_lib_momento_booth"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.0.0-dev.32", features = ["chrono"] }
derive_more = "0.99.17"
atom_table = "1.1.0"
ffsend-api = "0.7.3"
serde_json = "1.0.116"
chrono = "0.4.38"
image = { version = "0.25.1", features = ["rayon"] }
ipp = "5.0.3"
nokhwa = { git = "https://github.com/l1npengtul/nokhwa", branch="0.10", features = ["input-native", "output-threaded"] }
zune-jpeg = "0.4.11"
jpeg-encoder = "0.6.0"
static_init = "1.0.3"
lazy_static = "1.4.0"
dlopen = "0.1.8"
noise = "0.9.0"
dashmap = "5.5.3"
turborand = "0.10.1"
pathsep = "0.1.1"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
gphoto2 = "3.2.3"
ahash = "0.8.11"
img-parts = "0.3.0"
little_exif = "0.3.2"
url = "2.5.0"
num = "0.4.2"
num-traits = "0.2.18"
num-derive = "0.4.2"
rexiv2 = { version = "0.10.0", features = ["raw-tag-access"] }
thiserror = "1.0.59"

[profile.dev]
opt-level = 3
