[package]
name = "rust_lib_momento_booth"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { version = "=2.0.0", features = ["chrono"] }
anyhow = "1.0.86"
ffsend-api = "0.7.3"
serde_json = "1.0.119"
chrono = "0.4.38"
image = { version = "0.25.1", features = ["rayon"] }
ipp = "5.0.3"
zune-jpeg = "0.4.11"
jpeg-encoder = "0.6.0"
lazy_static = "1.5.0"
dlopen = "0.1.8"
noise = "0.9.0"
dashmap = "6.0.1"
turborand = "0.10.1"
pathsep = "0.1.1"
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
gphoto2 = "3.3.0"
ahash = "0.8.11"
img-parts = "0.3.0"
little_exif = "0.3.2"
url = "2.5.2"
num = "0.4.3"
num-traits = "0.2.19"
num-derive = "0.4.2"
rexiv2 = { version = "0.10.0", features = ["raw-tag-access"] }
regex = "1.10.5"
parking_lot = "0.12.3"
susync = "0.2.0"
rustc_version_runtime = "0.3.0"

[target.'cfg(unix)'.dependencies]
nokhwa = { git = "https://github.com/l1npengtul/nokhwa", branch="0.10", default-features = true, features = ["input-native", "output-threaded"] }

[target.'cfg(windows)'.dependencies]
nokhwa = { git = "https://github.com/l1npengtul/nokhwa", branch="0.10", default-features = false, features = ["input-native", "output-threaded"] }

[profile.dev]
opt-level = 3
